import type { Journey } from '../types';

export const deepHouse: Journey = {
  id: 'deep-house',
  name: 'Deep House',
  genre: 'deep-house',
  autoProgressInterval: 90,
  phases: [
    {
      id: 'dh-arrival',
      name: 'Arrival',
      effect: 'particles',
      colors: ['#FF6B35', '#F7C59F', '#EFEFD0', '#004E89'],
      backgroundColor: '#0A0A12',
      bassReactivity: 0.4,
      midReactivity: 0.3,
      highReactivity: 0.2,
      onsetReactivity: 0.3,
      intensity: 0.4,
      speed: 0.3,
      complexity: 0.4,
      postProcess: {
        bloomStrength: 0.3,
        bloomThreshold: 0.7,
        bloomRadius: 0.5,
        chromaticAberration: 0.003,
        feedbackAmount: 0.4,
        vignetteAmount: 0.4,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.6,
        warpIntensity: 0.4,
      },
      effectParams: { count: 1200, spread: 12, particleSize: 3.5, turbulence: 0.5, trails: 0.5 },
      transitionDuration: 3.5,
    },
    {
      id: 'dh-helix',
      name: 'Unwinding',
      effect: 'helix',
      colors: ['#2EC4B6', '#CBF3F0', '#FFBF69', '#FF9F1C'],
      backgroundColor: '#050510',
      bassReactivity: 0.5,
      midReactivity: 0.55,
      highReactivity: 0.35,
      onsetReactivity: 0.4,
      intensity: 0.55,
      speed: 0.4,
      complexity: 0.5,
      postProcess: {
        bloomStrength: 0.3,
        bloomThreshold: 0.7,
        bloomRadius: 0.6,
        chromaticAberration: 0.004,
        feedbackAmount: 0.2,
        vignetteAmount: 0.35,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.8,
        warpIntensity: 0.5,
      },
      effectParams: { twistSpeed: 0.5, helixRadius: 2.0, helixPitch: 10.0, waveAmplitude: 0.5 },
      transitionDuration: 3,
    },
    {
      id: 'dh-groove',
      name: 'Groove',
      effect: 'flowlines',
      colors: ['#2EC4B6', '#CBF3F0', '#FFBF69', '#FF9F1C'],
      backgroundColor: '#0A0A18',
      bassReactivity: 0.6,
      midReactivity: 0.5,
      highReactivity: 0.35,
      onsetReactivity: 0.45,
      intensity: 0.6,
      speed: 0.45,
      complexity: 0.5,
      postProcess: {
        bloomStrength: 0.3,
        bloomThreshold: 0.6,
        bloomRadius: 0.5,
        chromaticAberration: 0.005,
        feedbackAmount: 0.1,
        vignetteAmount: 0.3,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.0,
        warpIntensity: 0.6,
      },
      effectParams: { lineCount: 60, lineLength: 150, speed: 0.5, curvature: 0.7, thickness: 3 },
      transitionDuration: 2.5,
    },
    {
      id: 'dh-fractal',
      name: 'Meditation',
      effect: 'fractal',
      colors: ['#1B998B', '#2D3047', '#FFFD82', '#FF3366'],
      backgroundColor: '#020208',
      bassReactivity: 0.55,
      midReactivity: 0.65,
      highReactivity: 0.45,
      onsetReactivity: 0.4,
      intensity: 0.65,
      speed: 0.35,
      complexity: 0.7,
      postProcess: {
        bloomStrength: 0.4,
        bloomThreshold: 0.6,
        bloomRadius: 0.6,
        chromaticAberration: 0.006,
        feedbackAmount: 0.4,
        vignetteAmount: 0.25,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.7,
        warpIntensity: 0.7,
      },
      effectParams: { zoom: 0.9, iterations: 100, juliaReal: -0.7, juliaImag: 0.27, colorShift: 0, mode: 0 },
      transitionDuration: 3.5,
    },
    {
      id: 'dh-deep',
      name: 'Deep',
      effect: 'blob',
      colors: ['#E94560', '#FF6B9D', '#C44569', '#6C5CE7'],
      backgroundColor: '#080810',
      bassReactivity: 0.7,
      midReactivity: 0.5,
      highReactivity: 0.4,
      onsetReactivity: 0.5,
      intensity: 0.85,
      speed: 0.4,
      complexity: 0.6,
      postProcess: {
        bloomStrength: 0.6,
        bloomThreshold: 0.4,
        bloomRadius: 0.7,
        chromaticAberration: 0.006,
        feedbackAmount: 0.15,
        vignetteAmount: 0.2,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.6,
        warpIntensity: 0.3,
      },
      effectParams: { noiseScale: 2.0, noiseSpeed: 0.4, deformAmount: 0.7, smoothness: 0.6, glowIntensity: 1.2 },
      transitionDuration: 2.5,
    },
    {
      id: 'dh-metaballs',
      name: 'Liquid',
      effect: 'metaballs',
      colors: ['#FF6B6B', '#4ECDC4', '#45B7D1', '#96CEB4'],
      backgroundColor: '#060612',
      bassReactivity: 0.6,
      midReactivity: 0.55,
      highReactivity: 0.4,
      onsetReactivity: 0.5,
      intensity: 0.65,
      speed: 0.45,
      complexity: 0.55,
      postProcess: {
        bloomStrength: 0.3,
        bloomThreshold: 0.6,
        bloomRadius: 0.5,
        chromaticAberration: 0.005,
        feedbackAmount: 0.4,
        vignetteAmount: 0.3,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.9,
        warpIntensity: 0.55,
      },
      effectParams: { blobCount: 12, threshold: 3.5 },
      transitionDuration: 2.5,
    },
    {
      id: 'dh-afterglow',
      name: 'Afterglow',
      effect: 'waveformRing',
      colors: ['#FFD166', '#EF476F', '#06D6A0', '#118AB2'],
      backgroundColor: '#060610',
      bassReactivity: 0.7,
      midReactivity: 0.6,
      highReactivity: 0.5,
      onsetReactivity: 0.5,
      intensity: 0.9,
      speed: 0.35,
      complexity: 0.5,
      postProcess: {
        bloomStrength: 0.55,
        bloomThreshold: 0.5,
        bloomRadius: 0.6,
        chromaticAberration: 0.004,
        feedbackAmount: 0.4,
        vignetteAmount: 0.3,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.5,
        warpIntensity: 0.7,
      },
      effectParams: { radius: 3.0, amplitude: 3.5, rotation: 0.4, smoothing: 0.6, lineWidth: 4.0, segments: 256 },
      transitionDuration: 4,
    },
    {
      id: 'dh-starfield',
      name: 'Cosmos',
      effect: 'starfield',
      colors: ['#4ECDC4', '#556270', '#C7F464', '#FF6B6B'],
      backgroundColor: '#000008',
      bassReactivity: 0.6,
      midReactivity: 0.4,
      highReactivity: 0.3,
      onsetReactivity: 0.5,
      intensity: 0.6,
      speed: 0.4,
      complexity: 0.4,
      postProcess: {
        bloomStrength: 0.3,
        bloomThreshold: 0.7,
        bloomRadius: 0.4,
        chromaticAberration: 0.004,
        feedbackAmount: 0.35,
        vignetteAmount: 0.3,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.3,
        warpIntensity: 0.2,
      },
      effectParams: { warpSpeed: 1.0 },
      transitionDuration: 3.5,
    },
    {
      id: 'dh-aurora',
      name: 'Northern Lights',
      effect: 'aurora',
      colors: ['#00FF88', '#0088FF', '#FF00FF', '#00FFCC'],
      backgroundColor: '#000510',
      bassReactivity: 0.5,
      midReactivity: 0.5,
      highReactivity: 0.4,
      onsetReactivity: 0.3,
      intensity: 0.55,
      speed: 0.3,
      complexity: 0.5,
      postProcess: {
        bloomStrength: 0.4,
        bloomThreshold: 0.6,
        bloomRadius: 0.6,
        chromaticAberration: 0.003,
        feedbackAmount: 0.35,
        vignetteAmount: 0.35,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.5,
        warpIntensity: 0.5,
      },
      effectParams: { curtainCount: 5, waveHeight: 0.15 },
      transitionDuration: 4,
    },
    {
      id: 'dh-rings',
      name: 'Ripples',
      effect: 'rings',
      colors: ['#2EC4B6', '#CBF3F0', '#9D4EDD', '#FF006E'],
      backgroundColor: '#000011',
      bassReactivity: 0.7,
      midReactivity: 0.5,
      highReactivity: 0.3,
      onsetReactivity: 0.6,
      intensity: 0.6,
      speed: 0.4,
      complexity: 0.5,
      postProcess: {
        bloomStrength: 0.4,
        bloomThreshold: 0.7,
        bloomRadius: 0.5,
        chromaticAberration: 0.006,
        feedbackAmount: 0.4,
        vignetteAmount: 0.3,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.8,
        warpIntensity: 0.4,
      },
      effectParams: {},
      transitionDuration: 3,
    },
    {
      id: 'dh-soundwaves',
      name: 'Pulse',
      effect: 'soundwaves',
      colors: ['#48CAE4', '#0077B6', '#9D4EDD', '#222222'],
      backgroundColor: '#000022',
      bassReactivity: 0.6,
      midReactivity: 0.7,
      highReactivity: 0.5,
      onsetReactivity: 0.5,
      intensity: 0.65,
      speed: 0.5,
      complexity: 0.5,
      postProcess: {
        bloomStrength: 0.3,
        bloomThreshold: 0.6,
        bloomRadius: 0.4,
        chromaticAberration: 0.005,
        feedbackAmount: 0.35,
        vignetteAmount: 0.3,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.7,
        warpIntensity: 0.3,
      },
      effectParams: {},
      transitionDuration: 3,
    },
    {
      id: 'dh-psycheq',
      name: 'Psych EQ',
      effect: 'psychedelicEQ',
      colors: ['#9D4EDD', '#48CAE4', '#FF6B6B', '#FFE66D'],
      backgroundColor: '#000011',
      bassReactivity: 0.9,
      midReactivity: 0.7,
      highReactivity: 0.5,
      onsetReactivity: 0.8,
      intensity: 0.85,
      speed: 0.6,
      complexity: 0.7,
      postProcess: {
        bloomStrength: 0.3,
        bloomThreshold: 0.7,
        bloomRadius: 0.5,
        chromaticAberration: 0.01,
        feedbackAmount: 0.4,
        vignetteAmount: 0.15,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.2,
        warpIntensity: 0.5,
      },
      effectParams: {},
      transitionDuration: 2,
    },
    {
      id: 'dh-laser',
      name: 'Laser Show',
      effect: 'laserShow',
      colors: ['#00FF00', '#FF00FF', '#00FFFF', '#FFFF00'],
      backgroundColor: '#000000',
      bassReactivity: 0.8,
      midReactivity: 0.6,
      highReactivity: 0.5,
      onsetReactivity: 0.7,
      intensity: 0.8,
      speed: 0.6,
      complexity: 0.6,
      postProcess: {
        bloomStrength: 0.6,
        bloomThreshold: 0.65,
        bloomRadius: 0.6,
        chromaticAberration: 0.004,
        feedbackAmount: 0.3,
        vignetteAmount: 0.2,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.5,
        warpIntensity: 0.3,
      },
      effectParams: {},
      transitionDuration: 2.5,
    },
    {
      id: 'dh-nebula',
      name: 'Nebula',
      effect: 'nebula',
      colors: ['#9D4EDD', '#FF006E', '#00B4D8', '#FFD166'],
      backgroundColor: '#000008',
      bassReactivity: 0.5,
      midReactivity: 0.5,
      highReactivity: 0.4,
      onsetReactivity: 0.35,
      intensity: 0.55,
      speed: 0.3,
      complexity: 0.6,
      postProcess: {
        bloomStrength: 0.5,
        bloomThreshold: 0.5,
        bloomRadius: 0.7,
        chromaticAberration: 0.004,
        feedbackAmount: 0.4,
        vignetteAmount: 0.3,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.4,
        warpIntensity: 0.4,
      },
      effectParams: {},
      transitionDuration: 4,
    },
    {
      id: 'dh-waterripple',
      name: 'Rain',
      effect: 'waterRipple',
      colors: ['#48CAE4', '#0077B6', '#90E0EF', '#CAF0F8'],
      backgroundColor: '#000810',
      bassReactivity: 0.6,
      midReactivity: 0.4,
      highReactivity: 0.5,
      onsetReactivity: 0.6,
      intensity: 0.55,
      speed: 0.4,
      complexity: 0.5,
      postProcess: {
        bloomStrength: 0.3,
        bloomThreshold: 0.6,
        bloomRadius: 0.5,
        chromaticAberration: 0.003,
        feedbackAmount: 0.35,
        vignetteAmount: 0.35,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.6,
        warpIntensity: 0.4,
      },
      effectParams: {},
      transitionDuration: 3.5,
    },
    {
      id: 'dh-terrain',
      name: 'Landscape',
      effect: 'terrain',
      colors: ['#2EC4B6', '#06D6A0', '#FFD166', '#073B4C'],
      backgroundColor: '#000510',
      bassReactivity: 0.55,
      midReactivity: 0.45,
      highReactivity: 0.3,
      onsetReactivity: 0.4,
      intensity: 0.6,
      speed: 0.35,
      complexity: 0.5,
      postProcess: {
        bloomStrength: 0.3,
        bloomThreshold: 0.65,
        bloomRadius: 0.5,
        chromaticAberration: 0.004,
        feedbackAmount: 0.3,
        vignetteAmount: 0.3,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.5,
        warpIntensity: 0.3,
      },
      effectParams: {},
      transitionDuration: 3.5,
    },
  ],
};