import type { Journey } from '../types';

export const futureDisco: Journey = {
  id: 'future-disco',
  name: 'Future Disco',
  genre: 'future-disco',
  autoProgressInterval: 80,
  phases: [
    {
      id: 'fd-sunset',
      name: 'Sunset',
      effect: 'grid',
      colors: ['#F72585', '#7209B7', '#3A0CA3', '#4CC9F0'],
      backgroundColor: '#0D001A',
      bassReactivity: 0.5,
      midReactivity: 0.6,
      highReactivity: 0.5,
      onsetReactivity: 0.4,
      intensity: 0.55,
      speed: 0.45,
      complexity: 0.5,
      postProcess: {
        bloomStrength: 0.6,
        bloomThreshold: 0.65,
        bloomRadius: 0.5,
        chromaticAberration: 0.006,
        feedbackAmount: 0.4,
        vignetteAmount: 0.25,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.0,
        warpIntensity: 0.5,
      },
      effectParams: { gridSize: 50, scrollSpeed: 0.5, amplitude: 0.7, lineColor: 0xf72585, perspective: 0.8 },
      transitionDuration: 2.5,
    },
    {
      id: 'fd-helix',
      name: 'Helix',
      effect: 'helix',
      colors: ['#FF00FF', '#00FFFF', '#FFD700', '#FF1493'],
      backgroundColor: '#08000F',
      bassReactivity: 0.6,
      midReactivity: 0.7,
      highReactivity: 0.5,
      onsetReactivity: 0.55,
      intensity: 0.7,
      speed: 0.6,
      complexity: 0.6,
      postProcess: {
        bloomStrength: 0.7,
        bloomThreshold: 0.6,
        bloomRadius: 0.6,
        chromaticAberration: 0.007,
        feedbackAmount: 0.4,
        vignetteAmount: 0.2,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.2,
        warpIntensity: 0.6,
      },
      effectParams: { twistSpeed: 0.7, helixRadius: 2.2, helixPitch: 8.0, waveAmplitude: 0.6 },
      transitionDuration: 2,
    },
    {
      id: 'fd-neon',
      name: 'Neon',
      effect: 'tunnel',
      colors: ['#FF00FF', '#00FFFF', '#FF1493', '#7B2FBE'],
      backgroundColor: '#05000A',
      bassReactivity: 0.7,
      midReactivity: 0.6,
      highReactivity: 0.55,
      onsetReactivity: 0.6,
      intensity: 0.75,
      speed: 0.55,
      complexity: 0.6,
      postProcess: {
        bloomStrength: 0.4,
        bloomThreshold: 0.6,
        bloomRadius: 0.7,
        chromaticAberration: 0.01,
        feedbackAmount: 0.4,
        vignetteAmount: 0.15,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.5,
        warpIntensity: 0.7,
      },
      effectParams: { speed: 0.6, radius: 0.5, twist: 0.5, glow: 0.8, segments: 6 },
      transitionDuration: 2,
    },
    {
      id: 'fd-fractal',
      name: 'Kaleidofract',
      effect: 'fractal',
      colors: ['#FF6EC7', '#7DF9FF', '#FFF01F', '#FF00FF'],
      backgroundColor: '#000005',
      bassReactivity: 0.7,
      midReactivity: 0.8,
      highReactivity: 0.6,
      onsetReactivity: 0.6,
      intensity: 0.8,
      speed: 0.5,
      complexity: 0.8,
      postProcess: {
        bloomStrength: 0.7,
        bloomThreshold: 0.6,
        bloomRadius: 0.6,
        chromaticAberration: 0.008,
        kaleidoscopeSegments: 8,
        feedbackAmount: 0.3,
        vignetteAmount: 0.15,
        warpSpeed: 1.0,
        warpIntensity: 0.8,
      },
      effectParams: { zoom: 2.0, iterations: 120, juliaReal: -0.4, juliaImag: 0.6, colorShift: 0.5, mode: 0 },
      transitionDuration: 2.5,
    },
    {
      id: 'fd-funky',
      name: 'Funky',
      effect: 'waveformRing',
      colors: ['#FFD700', '#FF6EC7', '#00FF7F', '#FF4500'],
      backgroundColor: '#0A000F',
      bassReactivity: 0.8,
      midReactivity: 0.7,
      highReactivity: 0.65,
      onsetReactivity: 0.7,
      intensity: 0.85,
      speed: 0.6,
      complexity: 0.7,
      postProcess: {
        bloomStrength: 0.4,
        bloomThreshold: 0.6,
        bloomRadius: 0.7,
        chromaticAberration: 0.012,
        kaleidoscopeSegments: 6,
        feedbackAmount: 0.4,
        vignetteAmount: 0.1,
        warpSpeed: 1.4,
        warpIntensity: 0.7,
      },
      effectParams: { radius: 4.5, amplitude: 3.5, rotation: 0.4, smoothing: 0.5, lineWidth: 3.5, segments: 256 },
      transitionDuration: 2,
    },
    {
      id: 'fd-shatter',
      name: 'Shatter',
      effect: 'imageShatter',
      colors: ['#FF1493', '#FF69B4', '#FFB6C1', '#FF00FF'],
      backgroundColor: '#050008',
      bassReactivity: 0.85,
      midReactivity: 0.6,
      highReactivity: 0.5,
      onsetReactivity: 0.8,
      intensity: 0.8,
      speed: 0.65,
      complexity: 0.65,
      postProcess: {
        bloomStrength: 0.4,
        bloomThreshold: 0.6,
        bloomRadius: 0.6,
        chromaticAberration: 0.009,
        feedbackAmount: 0.4,
        vignetteAmount: 0.15,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.3,
        warpIntensity: 0.6,
      },
      effectParams: { explosionForce: 1.2, reformStrength: 0.5 },
      transitionDuration: 2,
    },
    {
      id: 'fd-metaballs',
      name: 'Morphing',
      effect: 'metaballs',
      colors: ['#7DF9FF', '#FF6EC7', '#DFFF00', '#BF00FF'],
      backgroundColor: '#03000A',
      bassReactivity: 0.7,
      midReactivity: 0.65,
      highReactivity: 0.55,
      onsetReactivity: 0.55,
      intensity: 0.75,
      speed: 0.55,
      complexity: 0.65,
      postProcess: {
        bloomStrength: 0.7,
        bloomThreshold: 0.6,
        bloomRadius: 0.6,
        chromaticAberration: 0.006,
        feedbackAmount: 0.4,
        vignetteAmount: 0.2,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.1,
        warpIntensity: 0.6,
      },
      effectParams: { blobCount: 12, threshold: 2.0 },
      transitionDuration: 2.5,
    },
    {
      id: 'fd-stardust',
      name: 'Stardust',
      effect: 'particles',
      colors: ['#E0AAFF', '#C77DFF', '#9D4EDD', '#5A189A'],
      backgroundColor: '#03000A',
      bassReactivity: 0.45,
      midReactivity: 0.5,
      highReactivity: 0.6,
      onsetReactivity: 0.4,
      intensity: 0.55,
      speed: 0.35,
      complexity: 0.55,
      postProcess: {
        bloomStrength: 0.6,
        bloomThreshold: 0.6,
        bloomRadius: 0.7,
        chromaticAberration: 0.005,
        feedbackAmount: 0.35,
        vignetteAmount: 0.35,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.7,
        warpIntensity: 0.65,
      },
      effectParams: { count: 2500, spread: 20, particleSize: 3, turbulence: 0.3, trails: 0.6 },
      transitionDuration: 3.5,
    },
    {
      id: 'fd-plasma',
      name: 'Plasma',
      effect: 'plasma',
      colors: ['#FF00FF', '#00FFCC', '#FFD700', '#FF1493'],
      backgroundColor: '#000005',
      bassReactivity: 0.7,
      midReactivity: 0.7,
      highReactivity: 0.5,
      onsetReactivity: 0.6,
      intensity: 0.75,
      speed: 0.5,
      complexity: 0.7,
      postProcess: {
        bloomStrength: 0.5,
        bloomThreshold: 0.6,
        bloomRadius: 0.5,
        chromaticAberration: 0.008,
        feedbackAmount: 0.4,
        vignetteAmount: 0.2,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.2,
        warpIntensity: 0.6,
      },
      effectParams: {},
      transitionDuration: 2.5,
    },
    {
      id: 'fd-kaleidoscope',
      name: 'Kaleidoscope',
      effect: 'geoKaleidoscope',
      colors: ['#FF6EC7', '#7DF9FF', '#FFF01F', '#BF00FF'],
      backgroundColor: '#000008',
      bassReactivity: 0.65,
      midReactivity: 0.7,
      highReactivity: 0.6,
      onsetReactivity: 0.55,
      intensity: 0.7,
      speed: 0.45,
      complexity: 0.6,
      postProcess: {
        bloomStrength: 0.7,
        bloomThreshold: 0.6,
        bloomRadius: 0.6,
        chromaticAberration: 0.007,
        feedbackAmount: 0.4,
        vignetteAmount: 0.2,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.0,
        warpIntensity: 0.6,
      },
      effectParams: { segments: 8, layers: 3, zoom: 3.0 },
      transitionDuration: 2.5,
    },
    {
      id: 'fd-equaliser',
      name: 'Spectrum',
      effect: 'equaliser',
      colors: ['#FF71CE', '#01CDFE', '#05FFA1', '#B967FF'],
      backgroundColor: '#0A0014',
      bassReactivity: 1.0,
      midReactivity: 1.0,
      highReactivity: 1.0,
      onsetReactivity: 0.8,
      intensity: 0.85,
      speed: 1.0,
      complexity: 0.5,
      postProcess: {
        bloomStrength: 0.3,
        bloomThreshold: 0.6,
        bloomRadius: 0.3,
        chromaticAberration: 0.006,
        feedbackAmount: 0.3,
        vignetteAmount: 0.2,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.5,
        warpIntensity: 0.2,
      },
      effectParams: {},
      transitionDuration: 2,
    },
    {
      id: 'fd-rings',
      name: 'Neon Rings',
      effect: 'rings',
      colors: ['#B967FF', '#FF71CE', '#01CDFE', '#FFFFFF'],
      backgroundColor: '#000011',
      bassReactivity: 0.8,
      midReactivity: 0.6,
      highReactivity: 0.4,
      onsetReactivity: 0.7,
      intensity: 0.75,
      speed: 0.55,
      complexity: 0.6,
      postProcess: {
        bloomStrength: 0.7,
        bloomThreshold: 0.6,
        bloomRadius: 0.5,
        chromaticAberration: 0.01,
        feedbackAmount: 0.4,
        vignetteAmount: 0.15,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.2,
        warpIntensity: 0.5,
      },
      effectParams: {},
      transitionDuration: 2,
    },
    {
      id: 'fd-morphpoly',
      name: 'Crystal',
      effect: 'morphPoly',
      colors: ['#B967FF', '#01CDFE', '#FF71CE', '#FFFFFF'],
      backgroundColor: '#000011',
      bassReactivity: 0.8,
      midReactivity: 0.6,
      highReactivity: 0.5,
      onsetReactivity: 0.7,
      intensity: 0.85,
      speed: 0.6,
      complexity: 0.7,
      postProcess: {
        bloomStrength: 0.4,
        bloomThreshold: 0.6,
        bloomRadius: 0.7,
        chromaticAberration: 0.01,
        feedbackAmount: 0.35,
        vignetteAmount: 0.1,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.3,
        warpIntensity: 0.6,
      },
      effectParams: {},
      transitionDuration: 2,
    },
    {
      id: 'fd-warpedtorus',
      name: 'Warp Knot',
      effect: 'warpedTorus',
      colors: ['#05FFA1', '#B967FF', '#FF71CE', '#01CDFE'],
      backgroundColor: '#000011',
      bassReactivity: 0.75,
      midReactivity: 0.7,
      highReactivity: 0.5,
      onsetReactivity: 0.7,
      intensity: 0.8,
      speed: 0.55,
      complexity: 0.6,
      postProcess: {
        bloomStrength: 0.7,
        bloomThreshold: 0.6,
        bloomRadius: 0.5,
        chromaticAberration: 0.008,
        feedbackAmount: 0.3,
        vignetteAmount: 0.15,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.5,
        warpIntensity: 0.7,
      },
      effectParams: {},
      transitionDuration: 2.5,
    },
  ],
};
