import type { Journey } from '../types';

export const peakTechno: Journey = {
  id: 'peak-techno',
  name: 'Peak Techno',
  genre: 'peak-techno',
  autoProgressInterval: 70,
  phases: [
    {
      id: 'pt-industrial',
      name: 'Industrial',
      effect: 'grid',
      colors: ['#FFFFFF', '#808080', '#404040', '#1A1A1A'],
      backgroundColor: '#000000',
      bassReactivity: 0.6,
      midReactivity: 0.3,
      highReactivity: 0.25,
      onsetReactivity: 0.5,
      intensity: 0.5,
      speed: 0.4,
      complexity: 0.4,
      postProcess: {
        bloomStrength: 0.4,
        bloomThreshold: 0.6,
        bloomRadius: 0.3,
        chromaticAberration: 0.004,
        feedbackAmount: 0.35,
        vignetteAmount: 0.5,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.2,
        warpIntensity: 0.5,
      },
      effectParams: { gridSize: 40, scrollSpeed: 0.5, amplitude: 0.5, lineColor: 0x808080, perspective: 0.9 },
      transitionDuration: 2,
    },
    {
      id: 'pt-metaballs',
      name: 'Ooze',
      effect: 'metaballs',
      colors: ['#FF0000', '#880000', '#440000', '#220000'],
      backgroundColor: '#000000',
      bassReactivity: 0.8,
      midReactivity: 0.4,
      highReactivity: 0.3,
      onsetReactivity: 0.7,
      intensity: 0.65,
      speed: 0.55,
      complexity: 0.6,
      postProcess: {
        bloomStrength: 0.3,
        bloomThreshold: 0.6,
        bloomRadius: 0.4,
        chromaticAberration: 0.006,
        feedbackAmount: 0.4,
        vignetteAmount: 0.35,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.5,
        warpIntensity: 0.7,
      },
      effectParams: { blobCount: 12, threshold: 1.8 },
      transitionDuration: 1.5,
    },
    {
      id: 'pt-build',
      name: 'Build',
      effect: 'tunnel',
      colors: ['#FF0000', '#CC0000', '#660000', '#1A0000'],
      backgroundColor: '#000000',
      bassReactivity: 0.8,
      midReactivity: 0.5,
      highReactivity: 0.45,
      onsetReactivity: 0.7,
      intensity: 0.75,
      speed: 0.65,
      complexity: 0.6,
      postProcess: {
        bloomStrength: 0.6,
        bloomThreshold: 0.65,
        bloomRadius: 0.5,
        chromaticAberration: 0.008,
        feedbackAmount: 0.4,
        vignetteAmount: 0.3,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.8,
        warpIntensity: 0.8,
      },
      effectParams: { speed: 0.7, radius: 0.4, twist: 0.7, glow: 0.9, segments: 4 },
      transitionDuration: 1.5,
    },
    {
      id: 'pt-fractal',
      name: 'Abyss',
      effect: 'fractal',
      colors: ['#FF0000', '#000000', '#FFFFFF', '#440000'],
      backgroundColor: '#000000',
      bassReactivity: 0.9,
      midReactivity: 0.6,
      highReactivity: 0.5,
      onsetReactivity: 0.8,
      intensity: 0.85,
      speed: 0.7,
      complexity: 0.9,
      postProcess: {
        bloomStrength: 0.7,
        bloomThreshold: 0.6,
        bloomRadius: 0.6,
        chromaticAberration: 0.012,
        feedbackAmount: 0.3,
        vignetteAmount: 0.15,
        kaleidoscopeSegments: 0,
        warpSpeed: 2.0,
        warpIntensity: 0.9,
      },
      effectParams: { zoom: 2.5, iterations: 150, juliaReal: -0.8, juliaImag: 0.156, colorShift: 0.2, mode: 2 },
      transitionDuration: 1,
    },
    {
      id: 'pt-drop',
      name: 'Drop',
      effect: 'blob',
      colors: ['#FFFFFF', '#FF0000', '#000000', '#1A1A1A'],
      backgroundColor: '#000000',
      bassReactivity: 1.0,
      midReactivity: 0.7,
      highReactivity: 0.6,
      onsetReactivity: 1.0,
      intensity: 1.0,
      speed: 0.8,
      complexity: 0.9,
      postProcess: {
        bloomStrength: 0.3,
        bloomThreshold: 0.6,
        bloomRadius: 0.8,
        chromaticAberration: 0.018,
        feedbackAmount: 0.4,
        vignetteAmount: 0.05,
        kaleidoscopeSegments: 0,
        warpSpeed: 2.5,
        warpIntensity: 1.0,
      },
      effectParams: { noiseScale: 3.0, noiseSpeed: 1.0, deformAmount: 1.2, smoothness: 0.25, glowIntensity: 1.0 },
      transitionDuration: 0.3,
    },
    {
      id: 'pt-shatter',
      name: 'Smash',
      effect: 'imageShatter',
      colors: ['#FFFFFF', '#FF0000', '#000000', '#808080'],
      backgroundColor: '#000000',
      bassReactivity: 1.0,
      midReactivity: 0.6,
      highReactivity: 0.5,
      onsetReactivity: 1.0,
      intensity: 0.95,
      speed: 0.8,
      complexity: 0.8,
      postProcess: {
        bloomStrength: 0.4,
        bloomThreshold: 0.6,
        bloomRadius: 0.7,
        chromaticAberration: 0.015,
        feedbackAmount: 0.35,
        vignetteAmount: 0.1,
        kaleidoscopeSegments: 0,
        warpSpeed: 2.2,
        warpIntensity: 0.85,
      },
      effectParams: { explosionForce: 1.8, reformStrength: 0.3 },
      transitionDuration: 0.5,
    },
    {
      id: 'pt-hypnotic',
      name: 'Hypnotic',
      effect: 'tunnel',
      colors: ['#39FF14', '#00FF00', '#0D0D0D', '#1A3300'],
      backgroundColor: '#000000',
      bassReactivity: 0.7,
      midReactivity: 0.4,
      highReactivity: 0.35,
      onsetReactivity: 0.6,
      intensity: 0.65,
      speed: 0.55,
      complexity: 0.5,
      postProcess: {
        bloomStrength: 0.7,
        bloomThreshold: 0.65,
        bloomRadius: 0.5,
        chromaticAberration: 0.007,
        kaleidoscopeSegments: 4,
        feedbackAmount: 0.35,
        vignetteAmount: 0.25,
        warpSpeed: 1.5,
        warpIntensity: 0.75,
      },
      effectParams: { speed: 0.6, radius: 0.35, twist: 0.9, glow: 0.7, segments: 8 },
      transitionDuration: 1.5,
    },
    {
      id: 'pt-helix',
      name: 'Spiral',
      effect: 'helix',
      colors: ['#39FF14', '#FF0000', '#FFFFFF', '#000000'],
      backgroundColor: '#000000',
      bassReactivity: 0.75,
      midReactivity: 0.5,
      highReactivity: 0.4,
      onsetReactivity: 0.6,
      intensity: 0.7,
      speed: 0.65,
      complexity: 0.6,
      postProcess: {
        bloomStrength: 0.6,
        bloomThreshold: 0.65,
        bloomRadius: 0.5,
        chromaticAberration: 0.006,
        feedbackAmount: 0.4,
        vignetteAmount: 0.25,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.3,
        warpIntensity: 0.6,
      },
      effectParams: { twistSpeed: 1.0, helixRadius: 1.5, helixPitch: 6.0, waveAmplitude: 0.7 },
      transitionDuration: 2,
    },
    {
      id: 'pt-breakdown',
      name: 'Breakdown',
      effect: 'particles',
      colors: ['#404040', '#808080', '#1A1A1A', '#0A0A0A'],
      backgroundColor: '#000000',
      bassReactivity: 0.3,
      midReactivity: 0.2,
      highReactivity: 0.25,
      onsetReactivity: 0.2,
      intensity: 0.25,
      speed: 0.15,
      complexity: 0.2,
      postProcess: {
        bloomStrength: 0.3,
        bloomThreshold: 0.7,
        bloomRadius: 0.3,
        chromaticAberration: 0.002,
        feedbackAmount: 0.45,
        vignetteAmount: 0.6,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.5,
        warpIntensity: 0.7,
      },
      effectParams: { count: 500, spread: 25, particleSize: 2, turbulence: 0.15, trails: 0.8 },
      transitionDuration: 3.5,
    },
    {
      id: 'pt-voronoi',
      name: 'Fracture',
      effect: 'voronoi',
      colors: ['#FF2200', '#FF6600', '#330000', '#FF4400'],
      backgroundColor: '#000000',
      bassReactivity: 0.85,
      midReactivity: 0.6,
      highReactivity: 0.5,
      onsetReactivity: 0.8,
      intensity: 0.7,
      speed: 0.6,
      complexity: 0.7,
      postProcess: {
        bloomStrength: 0.3,
        bloomThreshold: 0.6,
        bloomRadius: 0.4,
        chromaticAberration: 0.01,
        feedbackAmount: 0.35,
        vignetteAmount: 0.2,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.2,
        warpIntensity: 0.5,
      },
      effectParams: { cellCount: 10 },
      transitionDuration: 2,
    },
    {
      id: 'pt-starfield',
      name: 'Hyperdrive',
      effect: 'starfield',
      colors: ['#FFFFFF', '#00FFFF', '#FF0000', '#0000FF'],
      backgroundColor: '#000000',
      bassReactivity: 0.8,
      midReactivity: 0.5,
      highReactivity: 0.4,
      onsetReactivity: 0.7,
      intensity: 0.75,
      speed: 0.7,
      complexity: 0.5,
      postProcess: {
        bloomStrength: 0.3,
        bloomThreshold: 0.7,
        bloomRadius: 0.4,
        chromaticAberration: 0.008,
        feedbackAmount: 0.3,
        vignetteAmount: 0.15,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.5,
        warpIntensity: 0.3,
      },
      effectParams: { warpSpeed: 2.0 },
      transitionDuration: 2,
    },
    {
      id: 'pt-rings',
      name: 'Pulse Rings',
      effect: 'rings',
      colors: ['#FF00FF', '#00FFFF', '#FF0080', '#FFFFFF'],
      backgroundColor: '#000000',
      bassReactivity: 0.9,
      midReactivity: 0.5,
      highReactivity: 0.4,
      onsetReactivity: 0.8,
      intensity: 0.8,
      speed: 0.6,
      complexity: 0.7,
      postProcess: {
        bloomStrength: 0.7,
        bloomThreshold: 0.6,
        bloomRadius: 0.5,
        chromaticAberration: 0.01,
        feedbackAmount: 0.35,
        vignetteAmount: 0.2,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.5,
        warpIntensity: 0.6,
      },
      effectParams: {},
      transitionDuration: 2,
    },
    {
      id: 'pt-equaliser',
      name: 'EQ',
      effect: 'equaliser',
      colors: ['#00FF66', '#FFCC00', '#FF3300', '#FFFFFF'],
      backgroundColor: '#000000',
      bassReactivity: 1.0,
      midReactivity: 1.0,
      highReactivity: 1.0,
      onsetReactivity: 0.8,
      intensity: 0.9,
      speed: 1.0,
      complexity: 0.5,
      postProcess: {
        bloomStrength: 0.4,
        bloomThreshold: 0.7,
        bloomRadius: 0.3,
        chromaticAberration: 0.005,
        feedbackAmount: 0.3,
        vignetteAmount: 0.3,
        kaleidoscopeSegments: 0,
        warpSpeed: 0.5,
        warpIntensity: 0.2,
      },
      effectParams: {},
      transitionDuration: 1.5,
    },
    {
      id: 'pt-soundwaves',
      name: 'Oscilloscope',
      effect: 'soundwaves',
      colors: ['#00FF88', '#0088FF', '#FF00FF', '#333333'],
      backgroundColor: '#000000',
      bassReactivity: 0.9,
      midReactivity: 0.8,
      highReactivity: 0.7,
      onsetReactivity: 0.7,
      intensity: 0.85,
      speed: 0.8,
      complexity: 0.6,
      postProcess: {
        bloomStrength: 0.3,
        bloomThreshold: 0.6,
        bloomRadius: 0.4,
        chromaticAberration: 0.008,
        feedbackAmount: 0.4,
        vignetteAmount: 0.25,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.0,
        warpIntensity: 0.4,
      },
      effectParams: {},
      transitionDuration: 2,
    },
    {
      id: 'pt-morphpoly',
      name: 'Morph',
      effect: 'morphPoly',
      colors: ['#FF0044', '#FF8800', '#FFFFFF', '#8800FF'],
      backgroundColor: '#000000',
      bassReactivity: 0.9,
      midReactivity: 0.6,
      highReactivity: 0.5,
      onsetReactivity: 0.9,
      intensity: 0.9,
      speed: 0.7,
      complexity: 0.8,
      postProcess: {
        bloomStrength: 0.4,
        bloomThreshold: 0.6,
        bloomRadius: 0.6,
        chromaticAberration: 0.012,
        feedbackAmount: 0.35,
        vignetteAmount: 0.15,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.5,
        warpIntensity: 0.7,
      },
      effectParams: {},
      transitionDuration: 1.5,
    },
    {
      id: 'pt-warpedtorus',
      name: 'Twisted',
      effect: 'warpedTorus',
      colors: ['#FF00FF', '#00FFFF', '#FFFF00', '#FF4400'],
      backgroundColor: '#000000',
      bassReactivity: 0.85,
      midReactivity: 0.7,
      highReactivity: 0.5,
      onsetReactivity: 0.8,
      intensity: 0.85,
      speed: 0.65,
      complexity: 0.7,
      postProcess: {
        bloomStrength: 0.7,
        bloomThreshold: 0.6,
        bloomRadius: 0.6,
        chromaticAberration: 0.01,
        feedbackAmount: 0.35,
        vignetteAmount: 0.2,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.8,
        warpIntensity: 0.8,
      },
      effectParams: {},
      transitionDuration: 2,
    },
    {
      id: 'pt-psycheq',
      name: 'Psych EQ',
      effect: 'psychedelicEQ',
      colors: ['#FF0044', '#00FF88', '#FFCC00', '#FF00FF'],
      backgroundColor: '#000000',
      bassReactivity: 1.0,
      midReactivity: 0.8,
      highReactivity: 0.6,
      onsetReactivity: 0.9,
      intensity: 0.95,
      speed: 0.8,
      complexity: 0.8,
      postProcess: {
        bloomStrength: 0.4,
        bloomThreshold: 0.6,
        bloomRadius: 0.6,
        chromaticAberration: 0.014,
        feedbackAmount: 0.3,
        vignetteAmount: 0.1,
        kaleidoscopeSegments: 0,
        warpSpeed: 1.8,
        warpIntensity: 0.8,
      },
      effectParams: {},
      transitionDuration: 1.5,
    },
  ],
};
